<?php

namespace AppBundle\Repository;

/**
 * HubServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HubServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
