<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;

/**
 * ServiceTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceTypeRepository extends EntityRepository
{
    /**
     * @param int $page
     * @param int $maxPerPage
     * @return Pagerfanta
     */
    public function getResults($page = 1, $maxPerPage = 10)
    {
        $queryBuilder = $this->createQueryBuilder('s')
            ->select('s.id, s.number , s.amount, s.description, c.name region')
            ->join('s.country', 'c')
        ;

        $pager = new Pagerfanta(new DoctrineORMAdapter($queryBuilder, true, false));
        $pager->setMaxPerPage($maxPerPage);
        $pager->setCurrentPage($page);

        return $pager;
    }

    public function getServiceTypeWithCountry($id)
    {
        $queryBuilder = $this->createQueryBuilder('s')
            ->select('s.id, s.number , s.amount, s.description, s.tax, c.name region, m.isoCode')
            ->join('s.country', 'c')
            ->join('c.currency', 'm')
            ->where('s.id = ?1')
            ->setParameter(1, $id)
        ;

        return $queryBuilder->getQuery()->getSingleResult(Query::HYDRATE_ARRAY);
    }
}
